# Generated by Django 3.2.2 on 2023-07-04 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(db_index=True, max_length=50, unique=True)),
                ('password', models.CharField(db_index=True, max_length=100)),
            ],
        ),
    ]
