# Generated by Django 3.2.2 on 2023-07-01 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receiptdetail',
            name='quantity',
        ),
    ]
