# Generated by Django 3.2.2 on 2023-07-01 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0002_remove_receiptdetail_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receipt',
            old_name='payee',
            new_name='shop',
        ),
        migrations.RenameField(
            model_name='shopping',
            old_name='payee',
            new_name='shop',
        ),
        migrations.RemoveField(
            model_name='shopping',
            name='receipt',
        ),
        migrations.AddField(
            model_name='receipt',
            name='shopping',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shopping.shopping'),
        ),
    ]
